export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_OUT';


export const REGISTERING = 'REGISTERING';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';


export const FETCHING_ARTICLES = 'FETCHING_ARTICLES';
export const FETCHING_ARTICLES_SUCCESS = 'FETCHING_ARTICLES_SUCCESS';
export const FETCHING_ARTICLES_FAILED = 'FETCHING_ARTICLES_FAILED';

export const FETCHING_MY_ARTICLES = 'FETCHING_MY_ARTICLES';
export const FETCHING_MY_ARTICLES_SUCCESS = 'FETCHING_MY_ARTICLES_SUCCESS';
export const FETCHING_MY_ARTICLES_FAILED = 'FETCHING_MY_ARTICLES_FAILED';

export const CREATING_ARTICLE = 'CREATING_ARTICLE';
export const CREATING_ARTICLE_SUCCESS = 'CREATING_ARTICLE_SUCCESS';
export const CREATING_ARTICLE_FAILED = 'CREATING_ARTICLE_FAILED';
export const CLEAR_CREATING_ARTICLE = 'CLEAR_CREATING_ARTICLE';

export const FETCHING_ARTICLE_DETAILS = 'FETCHING_ARTICLE_DETAILS';
export const FETCHING_ARTICLE_DETAILS_SUCCESS = 'FETCHING_ARTICLE_DETAILS_SUCCESS';
export const FETCHING_ARTICLE_DETAILS_FAILED = 'FETCHING_ARTICLE_DETAILS_FAILED';
export const CLEARING_FETCHING_ARTICLE_DETAILS =  'CLEARING_FETCHING_ARTICLE_DETAILS';

export const ADDING_COMMENT_TO_ARTICLE = 'ADDING_COMMENT_TO_ARTICLE';
export const ADDING_COMMENT_TO_ARTICLE_SUCCESS = 'ADDING_COMMENT_TO_ARTICLE_SUCCESS';
export const ADDING_COMMENT_TO_ARTICLE_FAILED = 'ADDING_COMMENT_TO_ARTICLE_FAILED';
export const CLEAR_ADDING_COMMENT_TO_ARTICLE = 'CLEAR_ADDING_COMMENT_TO_ARTICLE_FAILED';

export const FETCHING_COMMENT_OF_ARTICLE = 'FETCHING_COMMENT_OF_ARTICLE';
export const FETCHING_COMMENT_OF_ARTICLE_SUCCESS = 'FETCHING_COMMENT_OF_ARTICLE_SUCCESS';
export const FETCHING_COMMENT_OF_ARTICLE_FAILED = 'FETCHING_COMMENT_OF_ARTICLE_FAILED';
export const CLEAR_FETCHING_COMMENT_OF_ARTICLE = 'CLEAR_FETCHING_COMMENT_OF_ARTICLE';


export const DELETING_COMMENT = 'DELETING_COMMENT';
export const DELETING_COMMENT_SUCCESS = 'DELETING_COMMENT_SUCCESS';
export const DELETING_COMMENT_FAILED = 'DELETING_COMMENT_FAILED';
export const CLEAR_DELETING_COMMENT = 'CLEAR_DELETING_COMMENT';

export const DELETING_ARTICLE = 'DELETING_ARTICLE';
export const DELETING_ARTICLE_SUCCESS = 'DELETING_ARTICLE_SUCCESS';
export const DELETING_ARTICLE_FAILED = 'DELETING_ARTICLE_FAILED';
export const CLEAR_DELETING_ARTICLE = 'CLEAR_DELETING_ARTICLE';


